# Generated by Django 4.2.6 on 2023-10-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='materials_provided',
        ),
        migrations.AddField(
            model_name='customer',
            name='materials_provided',
            field=models.ManyToManyField(blank=True, null=True, to='studentapp.material'),
        ),
    ]
